steps:
  - imports:
      align: group
      list_align: after_alias
      long_list_align: new_line
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
      post_qualify: false # Changed from true to false to fix position error
      sort: true
  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
  - trailing_whitespace: {}
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

columns: 120

newline: native

language_extensions:
  - OverloadedStrings
  - RecordWildCards

indent: 2
